### ISSUE TITLE
引入失败了

### ISSUE THREAD

**Issue by BennieMeng** [jbenner-radham/inquirer-radio-prompt#1]
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /node_modules/inquirer-radio-prompt/package.json

**Comment by BennieMeng** [comment]
maybe esm modal only reason

**Comment by jbenner-radham** [comment]
Hi, sorry for the delayed response. I think you're right and it's because it's ESM only. I created an ESM test project and it worked fine. But, when I created a CJS test project I got the same error you did.

If there's interest, I can look into making the package a dual ESM & CJS export though.

**Comment by jbenner-radham** [comment]
So, this issue piqued my interest in dual export packages. I researched it a bit and figured out a good implementation and just published [v1.3.0](https://github.com/jbenner-radham/inquirer-radio-prompt/releases/tag/v1.3.0) which exports both ESM and CJS.

I'm going to close out this issue. But, if you have any further input or questions please feel free to comment.
